export const ROUTING_PARAMS_CHANGED = 'ROUTING_PARAMS_CHANGED'
export const SET_SIDEBAR_VISIBILITY = 'SET_SIDEBAR_VISIBILITY'
export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN'
export const OPEN_DROPDOWN = Symbol('OPEN_DROPDOWN')
export const CLOSE_DROPDOWN = Symbol('CLOSE_DROPDOWN')
