export const ROUTING_PARAMS_CHANGED = 'ROUTING_PARAMS_CHANGED'
export const SET_SIDEBAR_VISIBILITY = Symbol('SET_SIDEBAR_VISIBILITY')
export const TOGGLE_DROPDOWN = Symbol('TOGGLE_DROPDOWN')
export const OPEN_DROPDOWN = Symbol('OPEN_DROPDOWN')
export const CLOSE_DROPDOWN = Symbol('CLOSE_DROPDOWN')

export const TOGGLE_SHOW_SETTINGS = 'TOGGLE_SHOW_SETTINGS'
export const HIDE_SETTINGS = 'HIDE_SETTINGS'
