#!/bin/bash -e

# Full path to script even $0 has symlinks.
# Reference: http://stackoverflow.com/a/246128/345718
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ ${SOURCE} != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

PROJ_DIR=${SCRIPT_DIR}/../..
exec mvn -f ${PROJ_DIR}/pom.xml -q exec:java -Dexec.args="$*"

