// This is an incomplete list of modules which don't have TypeScript types yet.
// They help to keep the compiler happy when using noImplicitAny.
// It would be better to have proper declarations, better still to get them from definitelytyped.org.
// Please keep this list sorted alphabetically:
declare module '@storybook/addon-storyshots'
declare module 'autoprefixer'
declare module 'copy-webpack-plugin'
declare module 'cssnano'
declare module 'faster-stable-stringify'
declare module 'normalizr' // TODO update normalizr to get typings
declare module 'postcss-calc'
declare module 'postcss-color-function'
declare module 'postcss-cssnext'
declare module 'postcss-custom-media'
declare module 'postcss-custom-properties'
declare module 'postcss-discard-duplicates'
declare module 'postcss-esplit'
declare module 'postcss-import'
declare module 'postcss-reporter'
declare module 'postcss-url'
declare module 'react-intl-aggregate-webpack-plugin'
declare module 'react-intl-flatten-webpack-plugin'
declare module 'react-intl/locale-data/en.js'
declare module 'react-loading'
declare module 'react-lorem-component'
declare module 'react-syntax-highlighter/languages/hljs/xml'
declare module 'react-syntax-highlighter/light'
declare module 'react-syntax-highlighter/styles/hljs'
declare module 'redux-immutable-state-invariant'
declare module 'redux-sac'
declare module 'redux-thunk'
declare module 'redux-watch'
declare module 'require.all'
declare module 'webpack-manifest-plugin'
