enum ValidationId {
    HTML_XML = "HTML_XML",
    NEW_LINE = "NEW_LINE",
    TAB = "TAB",
    JAVA_VARIABLES = "JAVA_VARIABLES",
    XML_ENTITY = "XML_ENTITY",
    PRINTF_VARIABLES = "PRINTF_VARIABLES",
    PRINTF_XSI_EXTENSION = "PRINTF_XSI_EXTENSION"
}

export default ValidationId
