<!-- 
  JBoss, the OpenSource J2EE webOS
  Distributable under LGPL license.
  See terms of license at gnu.org. 
 -->
<%@ page language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ page isELIgnored ="false" %>

<h1>Directory listing for: ${directory.fullPath}</h1>

<c:if test="${not empty directory.directories}">
<h2>Directories:</h2>
<c:forEach var="dir" items="${directory.directories}">
<a href="${dir.name}">${dir.name}</a><br />
</c:forEach>
</c:if>

<c:if test="${not empty directory.nodes}">
<h2>Files:</h2>
<c:forEach var="file" items="${directory.nodes}">
<a href="${file.name}">${file.name}</a><br />
</c:forEach>
</c:if>

<hr />
<p>Generated by <a href="http://labs.jboss.org/projects/shotoku">Shotoku</a>.</p>
