// flow-typed signature: b76d525386f1ce071b1d91b7b58479fb
// flow-typed version: <<STUB>>/babel-preset-react_v6.5.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-preset-react/index' {
  declare module.exports: $Exports<'babel-preset-react'>;
}
declare module 'babel-preset-react/index.js' {
  declare module.exports: $Exports<'babel-preset-react'>;
}
