// flow-typed signature: 1f1a2feeb1687b6d49da605f68855eda
// flow-typed version: <<STUB>>/chart.js_v2.6.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chart.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chart.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chart.js/dist/Chart.bundle' {
  declare module.exports: any;
}

declare module 'chart.js/dist/Chart.bundle.min' {
  declare module.exports: any;
}

declare module 'chart.js/dist/Chart' {
  declare module.exports: any;
}

declare module 'chart.js/dist/Chart.min' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-anchorjs/anchor-style' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart.bundle' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart.bundle.min' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart.min' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/chartjs-plugin-deferred' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/chartjs-plugin-deferred.min' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-fontsettings/fontsettings' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-ga/plugin' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-search-plus/jquery.mark.min' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-search-plus/search' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-sharing/buttons' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/gitbook' {
  declare module.exports: any;
}

declare module 'chart.js/dist/docs/gitbook/theme' {
  declare module.exports: any;
}

declare module 'chart.js/gulpfile' {
  declare module.exports: any;
}

declare module 'chart.js/karma.conf' {
  declare module.exports: any;
}

declare module 'chart.js/samples/charts/area/analyser' {
  declare module.exports: any;
}

declare module 'chart.js/samples/samples' {
  declare module.exports: any;
}

declare module 'chart.js/samples/utils' {
  declare module.exports: any;
}

declare module 'chart.js/src/chart' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Bar' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Bubble' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Doughnut' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Line' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.PolarArea' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Radar' {
  declare module.exports: any;
}

declare module 'chart.js/src/charts/Chart.Scatter' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.bar' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.bubble' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.doughnut' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.line' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.polarArea' {
  declare module.exports: any;
}

declare module 'chart.js/src/controllers/controller.radar' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.animation' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.canvasHelpers' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.controller' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.datasetController' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.element' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.helpers' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.interaction' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.layoutService' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.plugin' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.scale' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.scaleService' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.ticks' {
  declare module.exports: any;
}

declare module 'chart.js/src/core/core.tooltip' {
  declare module.exports: any;
}

declare module 'chart.js/src/elements/element.arc' {
  declare module.exports: any;
}

declare module 'chart.js/src/elements/element.line' {
  declare module.exports: any;
}

declare module 'chart.js/src/elements/element.point' {
  declare module.exports: any;
}

declare module 'chart.js/src/elements/element.rectangle' {
  declare module.exports: any;
}

declare module 'chart.js/src/platforms/platform.dom' {
  declare module.exports: any;
}

declare module 'chart.js/src/platforms/platform' {
  declare module.exports: any;
}

declare module 'chart.js/src/plugins/plugin.filler' {
  declare module.exports: any;
}

declare module 'chart.js/src/plugins/plugin.legend' {
  declare module.exports: any;
}

declare module 'chart.js/src/plugins/plugin.title' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.category' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.linear' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.linearbase' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.logarithmic' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.radialLinear' {
  declare module.exports: any;
}

declare module 'chart.js/src/scales/scale.time' {
  declare module.exports: any;
}

declare module 'chart.js/test/jasmine.context' {
  declare module.exports: any;
}

declare module 'chart.js/test/jasmine.index' {
  declare module.exports: any;
}

declare module 'chart.js/test/jasmine.matchers' {
  declare module.exports: any;
}

declare module 'chart.js/test/jasmine.utils' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/controller.bar.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/controller.bubble.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/controller.doughnut.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/controller.line.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/controller.polarArea.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/controller.radar.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/core.controller.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/core.datasetController.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/core.element.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/core.helpers.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/core.interaction.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/core.layoutService.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/core.plugin.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/core.scaleService.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/core.tooltip.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/element.arc.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/element.line.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/element.point.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/element.rectangle.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/global.defaults.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/global.deprecations.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/platform.dom.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/plugin.filler.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/plugin.legend.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/plugin.title.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/scale.category.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/scale.linear.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/scale.logarithmic.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/scale.radialLinear.tests' {
  declare module.exports: any;
}

declare module 'chart.js/test/specs/scale.time.tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chart.js/dist/Chart.bundle.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart.bundle'>;
}
declare module 'chart.js/dist/Chart.bundle.min.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart.bundle.min'>;
}
declare module 'chart.js/dist/Chart.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart'>;
}
declare module 'chart.js/dist/Chart.min.js' {
  declare module.exports: $Exports<'chart.js/dist/Chart.min'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-anchorjs/anchor-style.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-anchorjs/anchor-style'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart.bundle.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart.bundle'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart.bundle.min.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart.bundle.min'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart.min.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/Chart.min'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/chartjs-plugin-deferred.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/chartjs-plugin-deferred'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/chartjs-plugin-deferred.min.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-chartjs/chartjs-plugin-deferred.min'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-fontsettings/fontsettings.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-fontsettings/fontsettings'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-ga/plugin.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-ga/plugin'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-search-plus/jquery.mark.min.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-search-plus/jquery.mark.min'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-search-plus/search.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-search-plus/search'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook-plugin-sharing/buttons.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook-plugin-sharing/buttons'>;
}
declare module 'chart.js/dist/docs/gitbook/gitbook.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/gitbook'>;
}
declare module 'chart.js/dist/docs/gitbook/theme.js' {
  declare module.exports: $Exports<'chart.js/dist/docs/gitbook/theme'>;
}
declare module 'chart.js/gulpfile.js' {
  declare module.exports: $Exports<'chart.js/gulpfile'>;
}
declare module 'chart.js/karma.conf.js' {
  declare module.exports: $Exports<'chart.js/karma.conf'>;
}
declare module 'chart.js/samples/charts/area/analyser.js' {
  declare module.exports: $Exports<'chart.js/samples/charts/area/analyser'>;
}
declare module 'chart.js/samples/samples.js' {
  declare module.exports: $Exports<'chart.js/samples/samples'>;
}
declare module 'chart.js/samples/utils.js' {
  declare module.exports: $Exports<'chart.js/samples/utils'>;
}
declare module 'chart.js/src/chart.js' {
  declare module.exports: $Exports<'chart.js/src/chart'>;
}
declare module 'chart.js/src/charts/Chart.Bar.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Bar'>;
}
declare module 'chart.js/src/charts/Chart.Bubble.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Bubble'>;
}
declare module 'chart.js/src/charts/Chart.Doughnut.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Doughnut'>;
}
declare module 'chart.js/src/charts/Chart.Line.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Line'>;
}
declare module 'chart.js/src/charts/Chart.PolarArea.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.PolarArea'>;
}
declare module 'chart.js/src/charts/Chart.Radar.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Radar'>;
}
declare module 'chart.js/src/charts/Chart.Scatter.js' {
  declare module.exports: $Exports<'chart.js/src/charts/Chart.Scatter'>;
}
declare module 'chart.js/src/controllers/controller.bar.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.bar'>;
}
declare module 'chart.js/src/controllers/controller.bubble.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.bubble'>;
}
declare module 'chart.js/src/controllers/controller.doughnut.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.doughnut'>;
}
declare module 'chart.js/src/controllers/controller.line.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.line'>;
}
declare module 'chart.js/src/controllers/controller.polarArea.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.polarArea'>;
}
declare module 'chart.js/src/controllers/controller.radar.js' {
  declare module.exports: $Exports<'chart.js/src/controllers/controller.radar'>;
}
declare module 'chart.js/src/core/core.animation.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.animation'>;
}
declare module 'chart.js/src/core/core.canvasHelpers.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.canvasHelpers'>;
}
declare module 'chart.js/src/core/core.controller.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.controller'>;
}
declare module 'chart.js/src/core/core.datasetController.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.datasetController'>;
}
declare module 'chart.js/src/core/core.element.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.element'>;
}
declare module 'chart.js/src/core/core.helpers.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.helpers'>;
}
declare module 'chart.js/src/core/core.interaction.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.interaction'>;
}
declare module 'chart.js/src/core/core.js' {
  declare module.exports: $Exports<'chart.js/src/core/core'>;
}
declare module 'chart.js/src/core/core.layoutService.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.layoutService'>;
}
declare module 'chart.js/src/core/core.plugin.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.plugin'>;
}
declare module 'chart.js/src/core/core.scale.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.scale'>;
}
declare module 'chart.js/src/core/core.scaleService.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.scaleService'>;
}
declare module 'chart.js/src/core/core.ticks.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.ticks'>;
}
declare module 'chart.js/src/core/core.tooltip.js' {
  declare module.exports: $Exports<'chart.js/src/core/core.tooltip'>;
}
declare module 'chart.js/src/elements/element.arc.js' {
  declare module.exports: $Exports<'chart.js/src/elements/element.arc'>;
}
declare module 'chart.js/src/elements/element.line.js' {
  declare module.exports: $Exports<'chart.js/src/elements/element.line'>;
}
declare module 'chart.js/src/elements/element.point.js' {
  declare module.exports: $Exports<'chart.js/src/elements/element.point'>;
}
declare module 'chart.js/src/elements/element.rectangle.js' {
  declare module.exports: $Exports<'chart.js/src/elements/element.rectangle'>;
}
declare module 'chart.js/src/platforms/platform.dom.js' {
  declare module.exports: $Exports<'chart.js/src/platforms/platform.dom'>;
}
declare module 'chart.js/src/platforms/platform.js' {
  declare module.exports: $Exports<'chart.js/src/platforms/platform'>;
}
declare module 'chart.js/src/plugins/plugin.filler.js' {
  declare module.exports: $Exports<'chart.js/src/plugins/plugin.filler'>;
}
declare module 'chart.js/src/plugins/plugin.legend.js' {
  declare module.exports: $Exports<'chart.js/src/plugins/plugin.legend'>;
}
declare module 'chart.js/src/plugins/plugin.title.js' {
  declare module.exports: $Exports<'chart.js/src/plugins/plugin.title'>;
}
declare module 'chart.js/src/scales/scale.category.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.category'>;
}
declare module 'chart.js/src/scales/scale.linear.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.linear'>;
}
declare module 'chart.js/src/scales/scale.linearbase.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.linearbase'>;
}
declare module 'chart.js/src/scales/scale.logarithmic.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.logarithmic'>;
}
declare module 'chart.js/src/scales/scale.radialLinear.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.radialLinear'>;
}
declare module 'chart.js/src/scales/scale.time.js' {
  declare module.exports: $Exports<'chart.js/src/scales/scale.time'>;
}
declare module 'chart.js/test/jasmine.context.js' {
  declare module.exports: $Exports<'chart.js/test/jasmine.context'>;
}
declare module 'chart.js/test/jasmine.index.js' {
  declare module.exports: $Exports<'chart.js/test/jasmine.index'>;
}
declare module 'chart.js/test/jasmine.matchers.js' {
  declare module.exports: $Exports<'chart.js/test/jasmine.matchers'>;
}
declare module 'chart.js/test/jasmine.utils.js' {
  declare module.exports: $Exports<'chart.js/test/jasmine.utils'>;
}
declare module 'chart.js/test/specs/controller.bar.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/controller.bar.tests'>;
}
declare module 'chart.js/test/specs/controller.bubble.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/controller.bubble.tests'>;
}
declare module 'chart.js/test/specs/controller.doughnut.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/controller.doughnut.tests'>;
}
declare module 'chart.js/test/specs/controller.line.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/controller.line.tests'>;
}
declare module 'chart.js/test/specs/controller.polarArea.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/controller.polarArea.tests'>;
}
declare module 'chart.js/test/specs/controller.radar.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/controller.radar.tests'>;
}
declare module 'chart.js/test/specs/core.controller.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/core.controller.tests'>;
}
declare module 'chart.js/test/specs/core.datasetController.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/core.datasetController.tests'>;
}
declare module 'chart.js/test/specs/core.element.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/core.element.tests'>;
}
declare module 'chart.js/test/specs/core.helpers.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/core.helpers.tests'>;
}
declare module 'chart.js/test/specs/core.interaction.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/core.interaction.tests'>;
}
declare module 'chart.js/test/specs/core.layoutService.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/core.layoutService.tests'>;
}
declare module 'chart.js/test/specs/core.plugin.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/core.plugin.tests'>;
}
declare module 'chart.js/test/specs/core.scaleService.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/core.scaleService.tests'>;
}
declare module 'chart.js/test/specs/core.tooltip.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/core.tooltip.tests'>;
}
declare module 'chart.js/test/specs/element.arc.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/element.arc.tests'>;
}
declare module 'chart.js/test/specs/element.line.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/element.line.tests'>;
}
declare module 'chart.js/test/specs/element.point.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/element.point.tests'>;
}
declare module 'chart.js/test/specs/element.rectangle.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/element.rectangle.tests'>;
}
declare module 'chart.js/test/specs/global.defaults.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/global.defaults.tests'>;
}
declare module 'chart.js/test/specs/global.deprecations.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/global.deprecations.tests'>;
}
declare module 'chart.js/test/specs/platform.dom.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/platform.dom.tests'>;
}
declare module 'chart.js/test/specs/plugin.filler.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/plugin.filler.tests'>;
}
declare module 'chart.js/test/specs/plugin.legend.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/plugin.legend.tests'>;
}
declare module 'chart.js/test/specs/plugin.title.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/plugin.title.tests'>;
}
declare module 'chart.js/test/specs/scale.category.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/scale.category.tests'>;
}
declare module 'chart.js/test/specs/scale.linear.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/scale.linear.tests'>;
}
declare module 'chart.js/test/specs/scale.logarithmic.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/scale.logarithmic.tests'>;
}
declare module 'chart.js/test/specs/scale.radialLinear.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/scale.radialLinear.tests'>;
}
declare module 'chart.js/test/specs/scale.time.tests.js' {
  declare module.exports: $Exports<'chart.js/test/specs/scale.time.tests'>;
}
