// flow-typed signature: a16222e350a3b521e1373d7ca280090b
// flow-typed version: <<STUB>>/csso-loader_v0.0.6/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csso-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csso-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csso-loader/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csso-loader/index' {
  declare module.exports: $Exports<'csso-loader'>;
}
declare module 'csso-loader/index.js' {
  declare module.exports: $Exports<'csso-loader'>;
}
declare module 'csso-loader/test.js' {
  declare module.exports: $Exports<'csso-loader/test'>;
}
