// flow-typed signature: 7383a427d9708e996a8ecb8c1cf7b6ab
// flow-typed version: <<STUB>>/defined_v1.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'defined'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'defined' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'defined/example/defined' {
  declare module.exports: any;
}

declare module 'defined/test/def' {
  declare module.exports: any;
}

declare module 'defined/test/falsy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'defined/example/defined.js' {
  declare module.exports: $Exports<'defined/example/defined'>;
}
declare module 'defined/index' {
  declare module.exports: $Exports<'defined'>;
}
declare module 'defined/index.js' {
  declare module.exports: $Exports<'defined'>;
}
declare module 'defined/test/def.js' {
  declare module.exports: $Exports<'defined/test/def'>;
}
declare module 'defined/test/falsy.js' {
  declare module.exports: $Exports<'defined/test/falsy'>;
}
