// flow-typed signature: 67b266603a1036f98e852ac0b4920780
// flow-typed version: <<STUB>>/eslint-plugin-no-console-log_v1.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-no-console-log'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-no-console-log' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-no-console-log/lib/rules/no-console-log' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-no-console-log/index' {
  declare module.exports: $Exports<'eslint-plugin-no-console-log'>;
}
declare module 'eslint-plugin-no-console-log/index.js' {
  declare module.exports: $Exports<'eslint-plugin-no-console-log'>;
}
declare module 'eslint-plugin-no-console-log/lib/rules/no-console-log.js' {
  declare module.exports: $Exports<'eslint-plugin-no-console-log/lib/rules/no-console-log'>;
}
