// flow-typed signature: ada5112d570f3ee184ccd346ed1e2644
// flow-typed version: <<STUB>>/eslint-config-zanata_v2.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-zanata'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-zanata' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-zanata/angular' {
  declare module.exports: any;
}

declare module 'eslint-config-zanata/react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-zanata/angular.js' {
  declare module.exports: $Exports<'eslint-config-zanata/angular'>;
}
declare module 'eslint-config-zanata/index' {
  declare module.exports: $Exports<'eslint-config-zanata'>;
}
declare module 'eslint-config-zanata/index.js' {
  declare module.exports: $Exports<'eslint-config-zanata'>;
}
declare module 'eslint-config-zanata/react.js' {
  declare module.exports: $Exports<'eslint-config-zanata/react'>;
}
