// flow-typed signature: dfbe10adc9fbd5722d0bbbc3d255c0a6
// flow-typed version: <<STUB>>/fake-zanata-server_v3.0.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fake-zanata-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fake-zanata-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fake-zanata-server/js/configure-server' {
  declare module.exports: any;
}

declare module 'fake-zanata-server/js/get-json' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fake-zanata-server/index' {
  declare module.exports: $Exports<'fake-zanata-server'>;
}
declare module 'fake-zanata-server/index.js' {
  declare module.exports: $Exports<'fake-zanata-server'>;
}
declare module 'fake-zanata-server/js/configure-server.js' {
  declare module.exports: $Exports<'fake-zanata-server/js/configure-server'>;
}
declare module 'fake-zanata-server/js/get-json.js' {
  declare module.exports: $Exports<'fake-zanata-server/js/get-json'>;
}
