// flow-typed signature: 2f52975456bc9a2212a956ff8b9c5150
// flow-typed version: <<STUB>>/immutability-helper_v2.2.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutability-helper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutability-helper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'immutability-helper/index' {
  declare module.exports: $Exports<'immutability-helper'>;
}
declare module 'immutability-helper/index.js' {
  declare module.exports: $Exports<'immutability-helper'>;
}
