// flow-typed signature: e9ae8440cc523c289d31409ee0e2898c
// flow-typed version: <<STUB>>/moment-range_v2.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment-range/dist/moment-range' {
  declare module.exports: any;
}

declare module 'moment-range/dist/moment-range.min' {
  declare module.exports: any;
}

declare module 'moment-range/Gruntfile' {
  declare module.exports: any;
}

declare module 'moment-range/lib/moment-range' {
  declare module.exports: any;
}

declare module 'moment-range/test/moment-range' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment-range/dist/moment-range.js' {
  declare module.exports: $Exports<'moment-range/dist/moment-range'>;
}
declare module 'moment-range/dist/moment-range.min.js' {
  declare module.exports: $Exports<'moment-range/dist/moment-range.min'>;
}
declare module 'moment-range/Gruntfile.js' {
  declare module.exports: $Exports<'moment-range/Gruntfile'>;
}
declare module 'moment-range/lib/moment-range.js' {
  declare module.exports: $Exports<'moment-range/lib/moment-range'>;
}
declare module 'moment-range/test/moment-range.js' {
  declare module.exports: $Exports<'moment-range/test/moment-range'>;
}
