// flow-typed signature: 0235390d26e491e5639da4f7ee59e072
// flow-typed version: <<STUB>>/normalize.css_v3.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'normalize.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'normalize.css' {
  declare module.exports: any;
}
