// flow-typed signature: cb37882ca7dfba09c998194ed9ebf0b3
// flow-typed version: <<STUB>>/postcss-css-variables_v0.7.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-css-variables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-css-variables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-css-variables/lib/clone-splice-parent-onto-node-when' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/find-node-ancestor-with-selector' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/gather-variable-dependencies' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/generate-descendant-pieces-from-selector' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/generate-direct-descendant-pieces-from-selector' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/generate-scope-list' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/is-node-under-scope' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/is-piece-always-ancestor-selector' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/is-under-scope' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/resolve-decl' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/resolve-value' {
  declare module.exports: any;
}

declare module 'postcss-css-variables/lib/shallow-clone-node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-css-variables/index' {
  declare module.exports: $Exports<'postcss-css-variables'>;
}
declare module 'postcss-css-variables/index.js' {
  declare module.exports: $Exports<'postcss-css-variables'>;
}
declare module 'postcss-css-variables/lib/clone-splice-parent-onto-node-when.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/clone-splice-parent-onto-node-when'>;
}
declare module 'postcss-css-variables/lib/find-node-ancestor-with-selector.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/find-node-ancestor-with-selector'>;
}
declare module 'postcss-css-variables/lib/gather-variable-dependencies.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/gather-variable-dependencies'>;
}
declare module 'postcss-css-variables/lib/generate-descendant-pieces-from-selector.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/generate-descendant-pieces-from-selector'>;
}
declare module 'postcss-css-variables/lib/generate-direct-descendant-pieces-from-selector.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/generate-direct-descendant-pieces-from-selector'>;
}
declare module 'postcss-css-variables/lib/generate-scope-list.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/generate-scope-list'>;
}
declare module 'postcss-css-variables/lib/is-node-under-scope.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/is-node-under-scope'>;
}
declare module 'postcss-css-variables/lib/is-piece-always-ancestor-selector.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/is-piece-always-ancestor-selector'>;
}
declare module 'postcss-css-variables/lib/is-under-scope.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/is-under-scope'>;
}
declare module 'postcss-css-variables/lib/resolve-decl.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/resolve-decl'>;
}
declare module 'postcss-css-variables/lib/resolve-value.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/resolve-value'>;
}
declare module 'postcss-css-variables/lib/shallow-clone-node.js' {
  declare module.exports: $Exports<'postcss-css-variables/lib/shallow-clone-node'>;
}
