// flow-typed signature: c715140fd3c06893b1a217089b2d34ac
// flow-typed version: <<STUB>>/postcss-custom-properties_v6.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-custom-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-custom-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-custom-properties/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-custom-properties/dist/index.js' {
  declare module.exports: $Exports<'postcss-custom-properties/dist/index'>;
}
