// flow-typed signature: d64368880e567b2dc2db5d188471f2dd
// flow-typed version: <<STUB>>/postcss-bem-linter_v3.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-bem-linter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-bem-linter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-bem-linter/lib/check-implicit' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/constants' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/generate-config' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/get-selectors' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/list-sequences' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/preset-patterns' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/should-ignore-custom-property' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/should-ignore-rule' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/should-ignore-selector' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/to-interpolated-regexp' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/to-regexp' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/validate-custom-properties' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/validate-selectors' {
  declare module.exports: any;
}

declare module 'postcss-bem-linter/lib/validate-utilities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-bem-linter/index' {
  declare module.exports: $Exports<'postcss-bem-linter'>;
}
declare module 'postcss-bem-linter/index.js' {
  declare module.exports: $Exports<'postcss-bem-linter'>;
}
declare module 'postcss-bem-linter/lib/check-implicit.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/check-implicit'>;
}
declare module 'postcss-bem-linter/lib/constants.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/constants'>;
}
declare module 'postcss-bem-linter/lib/generate-config.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/generate-config'>;
}
declare module 'postcss-bem-linter/lib/get-selectors.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/get-selectors'>;
}
declare module 'postcss-bem-linter/lib/list-sequences.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/list-sequences'>;
}
declare module 'postcss-bem-linter/lib/preset-patterns.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/preset-patterns'>;
}
declare module 'postcss-bem-linter/lib/should-ignore-custom-property.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/should-ignore-custom-property'>;
}
declare module 'postcss-bem-linter/lib/should-ignore-rule.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/should-ignore-rule'>;
}
declare module 'postcss-bem-linter/lib/should-ignore-selector.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/should-ignore-selector'>;
}
declare module 'postcss-bem-linter/lib/to-interpolated-regexp.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/to-interpolated-regexp'>;
}
declare module 'postcss-bem-linter/lib/to-regexp.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/to-regexp'>;
}
declare module 'postcss-bem-linter/lib/validate-custom-properties.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/validate-custom-properties'>;
}
declare module 'postcss-bem-linter/lib/validate-selectors.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/validate-selectors'>;
}
declare module 'postcss-bem-linter/lib/validate-utilities.js' {
  declare module.exports: $Exports<'postcss-bem-linter/lib/validate-utilities'>;
}
