// flow-typed signature: b859d97a7197045fd7adb1642e709d86
// flow-typed version: <<STUB>>/postcss-vars_v0.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-vars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-vars' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-vars/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-vars/lib/index.js' {
  declare module.exports: $Exports<'postcss-vars/lib/index'>;
}
