// flow-typed signature: 8029f3d3e4e01f63786a908de7d55bf3
// flow-typed version: <<STUB>>/postcss-npm_v1.1.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-npm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-npm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-npm/lib/import' {
  declare module.exports: any;
}

declare module 'postcss-npm/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-npm/lib/import.js' {
  declare module.exports: $Exports<'postcss-npm/lib/import'>;
}
declare module 'postcss-npm/lib/index.js' {
  declare module.exports: $Exports<'postcss-npm/lib/index'>;
}
