// flow-typed signature: 47fe7c0c69db93cfd2d9841a4756ab4b
// flow-typed version: <<STUB>>/postcss-calc_v6.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-calc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-calc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-calc/dist/index' {
  declare module.exports: any;
}

declare module 'postcss-calc/dist/lib/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-calc/dist/index.js' {
  declare module.exports: $Exports<'postcss-calc/dist/index'>;
}
declare module 'postcss-calc/dist/lib/transform.js' {
  declare module.exports: $Exports<'postcss-calc/dist/lib/transform'>;
}
