// flow-typed signature: 3fd0a46163c4e498b0ae7ff722c286b9
// flow-typed version: <<STUB>>/react-styleguidist_v2.3.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-styleguidist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-styleguidist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-styleguidist/loaders/examples.loader' {
  declare module.exports: any;
}

declare module 'react-styleguidist/loaders/props.loader' {
  declare module.exports: any;
}

declare module 'react-styleguidist/loaders/styleguide.loader' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/build' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/make-webpack-config' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Components/Components' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Components/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Editor/Editor' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Editor/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Layout/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Layout/Layout' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Layout/Renderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Markdown/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Markdown/Markdown' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Playground/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Playground/Playground' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Preview/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Preview/Preview' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Props/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Props/Props' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ReactComponent/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ReactComponent/ReactComponent' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/ReactComponent/Renderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Section/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Section/Renderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Section/Section' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Sections/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Sections/Sections' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/StyleGuide/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/StyleGuide/StyleGuide' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/TableOfContents/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/TableOfContents/TableOfContents' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Wrapper/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/rsg-components/Wrapper/Wrapper' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/server' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/utils/codemirror-jsx' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/utils/config' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/utils/markdown' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/utils/server' {
  declare module.exports: any;
}

declare module 'react-styleguidist/src/utils/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-styleguidist/loaders/examples.loader.js' {
  declare module.exports: $Exports<'react-styleguidist/loaders/examples.loader'>;
}
declare module 'react-styleguidist/loaders/props.loader.js' {
  declare module.exports: $Exports<'react-styleguidist/loaders/props.loader'>;
}
declare module 'react-styleguidist/loaders/styleguide.loader.js' {
  declare module.exports: $Exports<'react-styleguidist/loaders/styleguide.loader'>;
}
declare module 'react-styleguidist/src/build.js' {
  declare module.exports: $Exports<'react-styleguidist/src/build'>;
}
declare module 'react-styleguidist/src/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/index'>;
}
declare module 'react-styleguidist/src/make-webpack-config.js' {
  declare module.exports: $Exports<'react-styleguidist/src/make-webpack-config'>;
}
declare module 'react-styleguidist/src/rsg-components/Components/Components.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Components/Components'>;
}
declare module 'react-styleguidist/src/rsg-components/Components/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Components/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Editor/Editor.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Editor/Editor'>;
}
declare module 'react-styleguidist/src/rsg-components/Editor/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Editor/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Layout/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Layout/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Layout/Layout.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Layout/Layout'>;
}
declare module 'react-styleguidist/src/rsg-components/Layout/Renderer.jsx' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Layout/Renderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Markdown/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Markdown/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Markdown/Markdown.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Markdown/Markdown'>;
}
declare module 'react-styleguidist/src/rsg-components/Playground/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Playground/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Playground/Playground.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Playground/Playground'>;
}
declare module 'react-styleguidist/src/rsg-components/Preview/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Preview/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Preview/Preview.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Preview/Preview'>;
}
declare module 'react-styleguidist/src/rsg-components/Props/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Props/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Props/Props.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Props/Props'>;
}
declare module 'react-styleguidist/src/rsg-components/ReactComponent/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ReactComponent/index'>;
}
declare module 'react-styleguidist/src/rsg-components/ReactComponent/ReactComponent.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ReactComponent/ReactComponent'>;
}
declare module 'react-styleguidist/src/rsg-components/ReactComponent/Renderer.jsx' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/ReactComponent/Renderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Section/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Section/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Section/Renderer.jsx' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Section/Renderer'>;
}
declare module 'react-styleguidist/src/rsg-components/Section/Section.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Section/Section'>;
}
declare module 'react-styleguidist/src/rsg-components/Sections/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Sections/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Sections/Sections.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Sections/Sections'>;
}
declare module 'react-styleguidist/src/rsg-components/StyleGuide/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/StyleGuide/index'>;
}
declare module 'react-styleguidist/src/rsg-components/StyleGuide/StyleGuide.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/StyleGuide/StyleGuide'>;
}
declare module 'react-styleguidist/src/rsg-components/TableOfContents/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/TableOfContents/index'>;
}
declare module 'react-styleguidist/src/rsg-components/TableOfContents/TableOfContents.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/TableOfContents/TableOfContents'>;
}
declare module 'react-styleguidist/src/rsg-components/Wrapper/index.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Wrapper/index'>;
}
declare module 'react-styleguidist/src/rsg-components/Wrapper/Wrapper.js' {
  declare module.exports: $Exports<'react-styleguidist/src/rsg-components/Wrapper/Wrapper'>;
}
declare module 'react-styleguidist/src/server.js' {
  declare module.exports: $Exports<'react-styleguidist/src/server'>;
}
declare module 'react-styleguidist/src/utils/codemirror-jsx.js' {
  declare module.exports: $Exports<'react-styleguidist/src/utils/codemirror-jsx'>;
}
declare module 'react-styleguidist/src/utils/config.js' {
  declare module.exports: $Exports<'react-styleguidist/src/utils/config'>;
}
declare module 'react-styleguidist/src/utils/markdown.js' {
  declare module.exports: $Exports<'react-styleguidist/src/utils/markdown'>;
}
declare module 'react-styleguidist/src/utils/server.js' {
  declare module.exports: $Exports<'react-styleguidist/src/utils/server'>;
}
declare module 'react-styleguidist/src/utils/utils.js' {
  declare module.exports: $Exports<'react-styleguidist/src/utils/utils'>;
}
