// flow-typed signature: 8e11d0185865bf182c460319a15fb3b6
// flow-typed version: <<STUB>>/react-date-range_v0.9.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-date-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-date-range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-date-range/lib/Calendar' {
  declare module.exports: any;
}

declare module 'react-date-range/lib/DateRange' {
  declare module.exports: any;
}

declare module 'react-date-range/lib/DayCell' {
  declare module.exports: any;
}

declare module 'react-date-range/lib/defaultRanges' {
  declare module.exports: any;
}

declare module 'react-date-range/lib/index' {
  declare module.exports: any;
}

declare module 'react-date-range/lib/LangDic' {
  declare module.exports: any;
}

declare module 'react-date-range/lib/PredefinedRanges' {
  declare module.exports: any;
}

declare module 'react-date-range/lib/styles' {
  declare module.exports: any;
}

declare module 'react-date-range/lib/utils/parseInput' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-date-range/lib/Calendar.js' {
  declare module.exports: $Exports<'react-date-range/lib/Calendar'>;
}
declare module 'react-date-range/lib/DateRange.js' {
  declare module.exports: $Exports<'react-date-range/lib/DateRange'>;
}
declare module 'react-date-range/lib/DayCell.js' {
  declare module.exports: $Exports<'react-date-range/lib/DayCell'>;
}
declare module 'react-date-range/lib/defaultRanges.js' {
  declare module.exports: $Exports<'react-date-range/lib/defaultRanges'>;
}
declare module 'react-date-range/lib/index.js' {
  declare module.exports: $Exports<'react-date-range/lib/index'>;
}
declare module 'react-date-range/lib/LangDic.js' {
  declare module.exports: $Exports<'react-date-range/lib/LangDic'>;
}
declare module 'react-date-range/lib/PredefinedRanges.js' {
  declare module.exports: $Exports<'react-date-range/lib/PredefinedRanges'>;
}
declare module 'react-date-range/lib/styles.js' {
  declare module.exports: $Exports<'react-date-range/lib/styles'>;
}
declare module 'react-date-range/lib/utils/parseInput.js' {
  declare module.exports: $Exports<'react-date-range/lib/utils/parseInput'>;
}
