// flow-typed signature: 61c6e33ad6af04b91d0d0458ce117b56
// flow-typed version: <<STUB>>/react-lorem-component_v0.12.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-lorem-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-lorem-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-lorem-component/index' {
  declare module.exports: $Exports<'react-lorem-component'>;
}
declare module 'react-lorem-component/index.js' {
  declare module.exports: $Exports<'react-lorem-component'>;
}
