// flow-typed signature: 020d8716cc8b38192af583b2da8c0153
// flow-typed version: <<STUB>>/react-toggle_v4.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-toggle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-toggle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-toggle/dist/component/check' {
  declare module.exports: any;
}

declare module 'react-toggle/dist/component/index' {
  declare module.exports: any;
}

declare module 'react-toggle/dist/component/util' {
  declare module.exports: any;
}

declare module 'react-toggle/dist/component/x' {
  declare module.exports: any;
}

declare module 'react-toggle/dist/docs/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-toggle/dist/component/check.js' {
  declare module.exports: $Exports<'react-toggle/dist/component/check'>;
}
declare module 'react-toggle/dist/component/index.js' {
  declare module.exports: $Exports<'react-toggle/dist/component/index'>;
}
declare module 'react-toggle/dist/component/util.js' {
  declare module.exports: $Exports<'react-toggle/dist/component/util'>;
}
declare module 'react-toggle/dist/component/x.js' {
  declare module.exports: $Exports<'react-toggle/dist/component/x'>;
}
declare module 'react-toggle/dist/docs/bundle.js' {
  declare module.exports: $Exports<'react-toggle/dist/docs/bundle'>;
}
