// flow-typed signature: 187ce004ef3a9d75c350a4db09ae19b7
// flow-typed version: <<STUB>>/react-intl-flatten-webpack-plugin_v0.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl-flatten-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl-flatten-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intl-flatten-webpack-plugin/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intl-flatten-webpack-plugin/index' {
  declare module.exports: $Exports<'react-intl-flatten-webpack-plugin'>;
}
declare module 'react-intl-flatten-webpack-plugin/index.js' {
  declare module.exports: $Exports<'react-intl-flatten-webpack-plugin'>;
}
declare module 'react-intl-flatten-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'react-intl-flatten-webpack-plugin/src/index'>;
}
