// flow-typed signature: fa51ceba5e7df5ef0998b8ac562b4bee
// flow-typed version: <<STUB>>/redux-sac_v0.5.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-sac'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-sac' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-sac/lib/cow-value-model' {
  declare module.exports: any;
}

declare module 'redux-sac/lib/node' {
  declare module.exports: any;
}

declare module 'redux-sac/lib/sac' {
  declare module.exports: any;
}

declare module 'redux-sac/lib/typed-action' {
  declare module.exports: any;
}

declare module 'redux-sac/src/cow-value-model' {
  declare module.exports: any;
}

declare module 'redux-sac/src/node' {
  declare module.exports: any;
}

declare module 'redux-sac/src/sac' {
  declare module.exports: any;
}

declare module 'redux-sac/src/typed-action' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-sac/lib/cow-value-model.js' {
  declare module.exports: $Exports<'redux-sac/lib/cow-value-model'>;
}
declare module 'redux-sac/lib/node.js' {
  declare module.exports: $Exports<'redux-sac/lib/node'>;
}
declare module 'redux-sac/lib/sac.js' {
  declare module.exports: $Exports<'redux-sac/lib/sac'>;
}
declare module 'redux-sac/lib/typed-action.js' {
  declare module.exports: $Exports<'redux-sac/lib/typed-action'>;
}
declare module 'redux-sac/src/cow-value-model.js' {
  declare module.exports: $Exports<'redux-sac/src/cow-value-model'>;
}
declare module 'redux-sac/src/node.js' {
  declare module.exports: $Exports<'redux-sac/src/node'>;
}
declare module 'redux-sac/src/sac.js' {
  declare module.exports: $Exports<'redux-sac/src/sac'>;
}
declare module 'redux-sac/src/typed-action.js' {
  declare module.exports: $Exports<'redux-sac/src/typed-action'>;
}
