// flow-typed signature: 7e66c9236988113d13baf8a58f43978b
// flow-typed version: <<STUB>>/redux-watch_v1.1.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'redux-watch/index' {
  declare module.exports: $Exports<'redux-watch'>;
}
declare module 'redux-watch/index.js' {
  declare module.exports: $Exports<'redux-watch'>;
}
