// flow-typed signature: 2def83f0827b2d19a4c6ceaf1f00708c
// flow-typed version: <<STUB>>/redux-api-middleware_v1.0.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-api-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-api-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-api-middleware/lib/CALL_API' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/lib/errors' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/lib/index' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/lib/middleware' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/lib/util' {
  declare module.exports: any;
}

declare module 'redux-api-middleware/lib/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-api-middleware/lib/CALL_API.js' {
  declare module.exports: $Exports<'redux-api-middleware/lib/CALL_API'>;
}
declare module 'redux-api-middleware/lib/errors.js' {
  declare module.exports: $Exports<'redux-api-middleware/lib/errors'>;
}
declare module 'redux-api-middleware/lib/index.js' {
  declare module.exports: $Exports<'redux-api-middleware/lib/index'>;
}
declare module 'redux-api-middleware/lib/middleware.js' {
  declare module.exports: $Exports<'redux-api-middleware/lib/middleware'>;
}
declare module 'redux-api-middleware/lib/util.js' {
  declare module.exports: $Exports<'redux-api-middleware/lib/util'>;
}
declare module 'redux-api-middleware/lib/validation.js' {
  declare module.exports: $Exports<'redux-api-middleware/lib/validation'>;
}
