// flow-typed signature: 51adf9a71e89f3bd30f06c0ade6dbcfd
// flow-typed version: <<STUB>>/redux-actions_v0.10.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-actions/lib/createAction' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/handleAction' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/handleActions' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/index' {
  declare module.exports: any;
}

declare module 'redux-actions/lib/ownKeys' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-actions/lib/createAction.js' {
  declare module.exports: $Exports<'redux-actions/lib/createAction'>;
}
declare module 'redux-actions/lib/handleAction.js' {
  declare module.exports: $Exports<'redux-actions/lib/handleAction'>;
}
declare module 'redux-actions/lib/handleActions.js' {
  declare module.exports: $Exports<'redux-actions/lib/handleActions'>;
}
declare module 'redux-actions/lib/index.js' {
  declare module.exports: $Exports<'redux-actions/lib/index'>;
}
declare module 'redux-actions/lib/ownKeys.js' {
  declare module.exports: $Exports<'redux-actions/lib/ownKeys'>;
}
