// flow-typed signature: 149d0effbd3edffe1187154961a641fe
// flow-typed version: <<STUB>>/storybook-host_v3.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-host'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-host' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook-host/lib/common/alignment' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/color' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/css' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/index' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/common/util' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/AlignmentContainer' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/ComponentHost' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/ComponentHost.stories' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/CropMark' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/components/CropMarks' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/decorators/host' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/index' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/index.test' {
  declare module.exports: any;
}

declare module 'storybook-host/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook-host/lib/common/alignment.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/alignment'>;
}
declare module 'storybook-host/lib/common/color.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/color'>;
}
declare module 'storybook-host/lib/common/css.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/css'>;
}
declare module 'storybook-host/lib/common/index.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/index'>;
}
declare module 'storybook-host/lib/common/util.js' {
  declare module.exports: $Exports<'storybook-host/lib/common/util'>;
}
declare module 'storybook-host/lib/components/AlignmentContainer.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/AlignmentContainer'>;
}
declare module 'storybook-host/lib/components/ComponentHost.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/ComponentHost'>;
}
declare module 'storybook-host/lib/components/ComponentHost.stories.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/ComponentHost.stories'>;
}
declare module 'storybook-host/lib/components/CropMark.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/CropMark'>;
}
declare module 'storybook-host/lib/components/CropMarks.js' {
  declare module.exports: $Exports<'storybook-host/lib/components/CropMarks'>;
}
declare module 'storybook-host/lib/decorators/host.js' {
  declare module.exports: $Exports<'storybook-host/lib/decorators/host'>;
}
declare module 'storybook-host/lib/index.js' {
  declare module.exports: $Exports<'storybook-host/lib/index'>;
}
declare module 'storybook-host/lib/index.test.js' {
  declare module.exports: $Exports<'storybook-host/lib/index.test'>;
}
declare module 'storybook-host/lib/types.js' {
  declare module.exports: $Exports<'storybook-host/lib/types'>;
}
