// flow-typed signature: 5c8ef1273e4eab808161e950aebbf396
// flow-typed version: <<STUB>>/suitcss-components-button-group_v2.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-components-button-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-components-button-group' {
  declare module.exports: any;
}
