// flow-typed signature: 1fef55a38c6b2dc8f69e6412ca356b6a
// flow-typed version: <<STUB>>/suitcss-utils-position_v0.2.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-utils-position'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-utils-position' {
  declare module.exports: any;
}
