// flow-typed signature: adcf849b0d8a20a659852483b9b59461
// flow-typed version: <<STUB>>/suitcss-utils-layout_v0.4.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-utils-layout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-utils-layout' {
  declare module.exports: any;
}
