// flow-typed signature: 41d078f596535057c2112361f0c93080
// flow-typed version: <<STUB>>/suitcss-utils-size_v0.7.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-utils-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-utils-size' {
  declare module.exports: any;
}
