// flow-typed signature: a213ce949f6aedad6f652bc68b4c8d73
// flow-typed version: <<STUB>>/suitcss-utils-display_v0.4.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-utils-display'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-utils-display' {
  declare module.exports: any;
}
