// flow-typed signature: 38cbc785df1341580b19affc4db576ff
// flow-typed version: <<STUB>>/suitcss-utils-text_v0.4.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-utils-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-utils-text' {
  declare module.exports: any;
}
