// flow-typed signature: 0986f53e1a2e9076146ee4610b5a76e8
// flow-typed version: <<STUB>>/suitcss-components-button_v4.0.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'suitcss-components-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'suitcss-components-button' {
  declare module.exports: any;
}
