// flow-typed signature: a4ba13e612857f0afbbc40851c261a1f
// flow-typed version: <<STUB>>/svg-sprite_v1.3.6/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-sprite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-sprite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-sprite/bin/svg-sprite' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/config' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/layouter' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/mode/base' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/mode/css' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/mode/css/packer' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/mode/defs' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/mode/stack' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/mode/standalone' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/mode/symbol' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/mode/view' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/queue' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/shape' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/shape/dimensions.phantom' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/sprite' {
  declare module.exports: any;
}

declare module 'svg-sprite/lib/svg-sprite/transform/svgo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-sprite/bin/svg-sprite.js' {
  declare module.exports: $Exports<'svg-sprite/bin/svg-sprite'>;
}
declare module 'svg-sprite/lib/svg-sprite.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite'>;
}
declare module 'svg-sprite/lib/svg-sprite/config.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/config'>;
}
declare module 'svg-sprite/lib/svg-sprite/layouter.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/layouter'>;
}
declare module 'svg-sprite/lib/svg-sprite/mode/base.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/mode/base'>;
}
declare module 'svg-sprite/lib/svg-sprite/mode/css.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/mode/css'>;
}
declare module 'svg-sprite/lib/svg-sprite/mode/css/packer.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/mode/css/packer'>;
}
declare module 'svg-sprite/lib/svg-sprite/mode/defs.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/mode/defs'>;
}
declare module 'svg-sprite/lib/svg-sprite/mode/stack.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/mode/stack'>;
}
declare module 'svg-sprite/lib/svg-sprite/mode/standalone.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/mode/standalone'>;
}
declare module 'svg-sprite/lib/svg-sprite/mode/symbol.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/mode/symbol'>;
}
declare module 'svg-sprite/lib/svg-sprite/mode/view.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/mode/view'>;
}
declare module 'svg-sprite/lib/svg-sprite/queue.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/queue'>;
}
declare module 'svg-sprite/lib/svg-sprite/shape.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/shape'>;
}
declare module 'svg-sprite/lib/svg-sprite/shape/dimensions.phantom.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/shape/dimensions.phantom'>;
}
declare module 'svg-sprite/lib/svg-sprite/sprite.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/sprite'>;
}
declare module 'svg-sprite/lib/svg-sprite/transform/svgo.js' {
  declare module.exports: $Exports<'svg-sprite/lib/svg-sprite/transform/svgo'>;
}
