// flow-typed signature: 40bd33d0955a4297d4e108a82a03940d
// flow-typed version: <<STUB>>/text-diff_v1.0.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-diff' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'text-diff/diff' {
  declare module.exports: any;
}

// Filename aliases
declare module 'text-diff/diff.js' {
  declare module.exports: $Exports<'text-diff/diff'>;
}
