name: Verify

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "porscheinformatik/zanata-server"
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
          server-id: sonatype-snapshots
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Deploy SNAPSHOT to Central
        run: |
          cd deploy-test
          mvn -e -V --builder singlethreaded -batch-mode deploy -DskipTests -Dgpg.passphrase="${{secrets.GPG_PASSPHRASE}}"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
