name: Verify

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "porscheinformatik/zanata-server"
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: temurin
      - name: Build with Maven
        run: mvn -e -V --builder singlethreaded -batch-mode -Dstyle.color=never --update-snapshots -Doptimise -Dkotlin.compiler.incremental=false -DskipFuncTests -DskipArqTests -Dappserver=wildfly8 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean install
      - name: Build Docker image
        run: |
          cp ./server/zanata-war/target/zanata-*.war ./server/docker/zanata.war
          docker build -t $IMAGE_NAME ./server/docker
